# Generated by Django 4.1 on 2022-09-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('DNI', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
                ('nivel_del_cliente', models.CharField(max_length=40)),
                ('dinero_en_la_cuenta', models.IntegerField()),
                ('tarjeta_de_credito_vencida', models.BooleanField()),
                ('fecha_de_vencimiento_tarjeta', models.DateField()),
                ('numero_de_tarjeta', models.IntegerField()),
                ('codigo_de_seguridad_tarjeta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_nuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('DNI', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
        migrations.RenameModel(
            old_name='Transferencias_bancarias',
            new_name='Transferencias_bancaria',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
