# Generated by Django 4.1 on 2022-09-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0002_cliente_usuario_nuevo_rename_empleados_empleado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transferencias_bancaria',
            new_name='Transferencia_bancaria',
        ),
    ]
