# Generated by Django 4.1 on 2022-10-11 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_1', '0007_cliente_dni_cliente_domicilio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empleado',
            name='domicilio',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='localidad',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='provincia',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='DNI',
            field=models.IntegerField(),
        ),
    ]
