# Generated by Django 4.1 on 2022-10-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0009_remove_transferencia_bancaria_id_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregar_dinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
