# Generated by Django 4.1 on 2022-10-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0010_agregar_dinero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agregar_dinero',
        ),
        migrations.RemoveField(
            model_name='transferencia_bancaria',
            name='destinatario_cliente_del_banco',
        ),
    ]
