# Generated by Django 4.1 on 2022-10-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0011_delete_agregar_dinero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_de_ingreso_a_la_empresa',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='posicion_laboral',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='sueldo_en_pesos',
        ),
    ]
