# Generated by Django 4.1 on 2022-10-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0012_remove_empleado_fecha_de_ingreso_a_la_empresa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_nuevo',
        ),
    ]
